### ISSUE TITLE
[Feature Request] Cmd Line Client

### ISSUE THREAD

**Issue by jeffythedragonslayer** [Skarsnik/QUsb2snes#105]
It would be nice if there were a command line app of QFile2Snes, to do things like copy ROMs and reset into them, so that this can be done from scripts.

**Comment by Skarsnik** [comment]
You can find one at https://github.com/usb2snes/usb2snes-cli 
There a build generated on each commit, for eg https://github.com/usb2snes/usb2snes-cli/actions/runs/1606412886
