### ISSUE TITLE
Cannot Change or Reset in macOS Monterey

### ISSUE THREAD

**Issue by taizen-lav** [Skarsnik/QUsb2snes#110]
After first setting which emulator I'm using, the client simply runs without any windows showing.  I get a message from the OS asking if I want to allow connections for it through the Firewall, which I allow, but that's it.

I never again get the option to choose an emulator.  I can't find the files to remove to perhaps reset it, and the only menu that shows is the application's menu.
![Screen Shot 2022-03-05 at 11 21 20 PM](https://user-images.githubusercontent.com/34722860/156910361-30ce8841-5941-465b-bdf1-a50922146a0d.png)

None of the windows or menus described on the website appear.  The locations described for Linux don't appear, either, even if I reveal hidden files and folders.  Not sure what to do.

I've changed emulators in the hopes that I can get things to work.  Please advise.

I'm running:
- macOS Monterey (12.2.1)
- Apple M1 processor, 16 GB RAM

Thank you.

**Comment by taizen-lav** [comment]
I'm using the latest, [v0.7.22.1](https://github.com/Skarsnik/QUsb2snes/tree/v0.7.22.1).

**Comment by Skarsnik** [comment]
QUsb2Snes does not have a window UI, it's just a system tray icon, it should show on the top right near the hour.
I don't have a VM with Montery.

![image](https://user-images.githubusercontent.com/12981631/156918913-db645ba9-bee1-4332-b6bf-a6e6f805f20b.png)

**Comment by taizen-lav** [comment]
Thank you.  Had an app that hid some of those items in the menu bar.  I see it now.

However...

Using RetroArch, it keeps saying that there is a timeout or the host is unreachable.  Again, the firewall is allowing connections.  I even added RetroArch manually to ensure it could connect.
![Screen Shot 2022-03-06 at 6 55 48 AM](https://user-images.githubusercontent.com/34722860/156924207-35dc1cf1-2275-436f-84ce-585fdadfe4b4.png)
![Screen Shot 2022-03-06 at 6 51 16 AM](https://user-images.githubusercontent.com/34722860/156924018-f10b9624-e373-4cdf-a0c5-9c8d0af45dca.png)

I'm wondering if there's a port setting I'm not aware of or if there's an additional security measure in Monterey.  Thoughts?

**Comment by TarThoron** [comment]
I'm not sure if still an issue, but older versions of RA for Mac (as recent as 1.9.0) don't actually enable Network Commands when you turn them on, either through the menu or editing the config file. You have to actually have to build from source and turn them on in the process.

This build has them on. I don't know of any more recent pre-built version that has them on.
[RetroArch-1.9.0-macos-qusb.zip](https://github.com/Skarsnik/QUsb2snes/files/8192765/RetroArch-1.9.0-macos-qusb.zip)

**Comment by taizen-lav** [comment]
That was the hint I was looking for.

I'm running the latest version of RetroArch, 1.10.1.  I could not enable network commands in the UI, but I found it in the config file.  I set it to "true", saved, ran RetroArch, and everything started communicating once I ran an SNES game.  Verified my tracker picks up automatically.

Thank you so much!  Have a good day.
