### ISSUE TITLE
Potentially use BizHawk comm.socket* interface in lua bridge

### ISSUE THREAD

**Issue by ianmcorvidae** [Skarsnik/QUsb2snes#115]
Hello and thank you for the hard work on this!

I'm attempting to use QUsb2snes on Linux with Bizhawk, which has somewhat new/somewhat particular Lua support (see e.g. https://github.com/TASEmulators/BizHawk/issues/2951 ). In particular, the use of `socket.core` seems to fail on (at least) Debian-based systems (noted in the issue above -- I also tried, locally, to create some symlinks to put things in places BizHawk appears to expect them, but simply got errors about dynamic libraries not being supported), and one proposed solution there was to use Bizhawk's integrated socket functions, described on https://tasvideos.org/Bizhawk/LuaFunctions and added in https://github.com/TASEmulators/BizHawk/pull/1080

I lack the requisite Lua expertise/understanding to add this, but as far as I can tell this route is the closest folks seem to have gotten for getting anything on Linux to use Lua/talk to outside programs, so I thought I'd file an issue to see if it's a simple change.

**Comment by ShneekeyTheLost** [comment]
Will NWA be able to interface appropriately with tools such as SNI or QUsb2snes with respect to multiworld servers such as Archipelago? I'm really hoping to use BizHawk in lieu of running SNES9x-rr for running things like LTTPR + AP.

**Comment by Skarsnik** [comment]
Enable Emulator Network Access support on qusb and try

https://github.com/Skarsnik/Bizhawk-nwa-tool/releases/tag/beta1
