### ISSUE TITLE
multi selectable radio buttons

### ISSUE THREAD

**Issue by jeffythedragonslayer** [Skarsnik/QUsb2snes#117]
I suggest changing these radio buttons to check boxes because multiple devices can be selected:

![image](https://user-images.githubusercontent.com/13253146/177660741-87b8c045-2d9a-4e07-a2d8-760fc34286dc.png)

**Comment by Skarsnik** [comment]
I still kinda prefer this way for 2 reasons :
- Users will likely only choose one
- I fear that some people will see checkboxes at something they have to check everything or be more afraid to mess up.

**Comment by Skarsnik** [comment]
This dialog get changed. Closing the issue
