### ISSUE TITLE
[SNES Classic] QUSB2SNES doesn't work w/ USB Host or Wifi

### ISSUE THREAD

**Issue by shinji257** [Skarsnik/QUsb2snes#22]
QUSB2SNES in SNES Classic mode doesn't work if either USB Host or Wifi is in use due to their reliance on OTG functionality through the micro USB port.  Currently it seems that QUSB2SNES is relying on a direct connection to the back of the SNES Classic right now.

Can we extend this to allow a connection over Wifi at all?  I don't know how feasible this would be at all but asking none the less.

**Comment by Skarsnik** [comment]
I could add an option to specify the ip on the console

**Comment by shinji257** [comment]
That would be useful if you could do that. :)

No rush on time though.

**Comment by shinji257** [comment]
👍 Thanks for this.  It works well.  I do notice a silent crash if it doesn't get a connection after a little bit with this but holds fine if you start it last.

For anyone else coming across this feature request you can find the SNES Mini IP via Wifi by checking your router, checking Hakchi's debug log if you use that version (it gets mentioned as IP after the first service added entry), or by logging into the device via telnet (which you can do quickly via Hakchi) where it shows both in telnet and if you run `ifconfig` in the terminal after logging in as `root`.

It is strongly suggested that once you get the ip address that you also set up an ip reservation in your router to try and make sure it sticks so you don't have to update the router ip regularly.
