### ISSUE TITLE
[Linux] Add support for no system tray

### ISSUE THREAD

**Issue by alercah** [Skarsnik/QUsb2snes#26]
I use Linux and don't normally use a system tray. It took me a long time to realize that the only interface to configure QUsb2snes is a system tray icon, since there was nothing visible. It would be nice to have an interface that din't require a tray.

**Comment by Skarsnik** [comment]
Hm, would you be fine if I just document all the setting of the config file (for now)? The Ui is not that useful on Linux anyways for now. I don't have much time to a "new" Ui for now and complete the Linux integration.

**Comment by alercah** [comment]
Yes, that would definitely work. Possibly also adding a log entry in the startup like "Connecting to system tray" or the like that points in that direction?

**Comment by cassidoxa** [comment]
I'd be interested in a no-taskbar qusb2snes as well. I got it working with retroarch with a taskbar in my WM, but it won't connect without right clicking on the taskbar icon.

**Comment by Skarsnik** [comment]
You can try QUsb2Snes -nogui 
Most support create the device (connect) when something ask for the list of devices.

**Comment by cassidoxa** [comment]
That worked, thanks!
