### ISSUE TITLE
Multibridge.lua crashes snes9x with corrupt heap

### ISSUE THREAD

**Issue by animamachinae** [Skarsnik/QUsb2snes#28]
This crash happens regularly about 30 seconds after loading the multibridge.lua file. It says the lua file connects correctly. I'm attempting to open a A Link to the Past randomized rom, I've tried multiple roms and it crashes on all of them. Sometimes snes9x glitches to have no video output, and in that case the lua file does not crash. I've attached the debug logs created by using the debug option from the tray. Also attached is the event viewer error, and the expanded data from the report.wer file created when it crashes. Any help would be greatly appreciated.

[log-debug.txt](https://github.com/Skarsnik/QUsb2snes/files/3394911/log-debug.txt)
[event_viewer_error.txt](https://github.com/Skarsnik/QUsb2snes/files/3394929/event_viewer_error.txt)
[event_viewer_crash_log.txt](https://github.com/Skarsnik/QUsb2snes/files/3394927/event_viewer_crash_log.txt)

**Comment by Skarsnik** [comment]
Maybe you can try the instruction on http://multitroid.com/ to fix the crash (downloading the right VC redist)

**Comment by animamachinae** [comment]
I tried downloading and installing the redists and then restarting and it still crashes about 30 seconds after running the lua with a corrupted heap. I'm going to try and run it on a separate computer and just see if that works to see if it's a me problem or my computer problem.

**Comment by animamachinae** [comment]
So I tried it on a different computer and it works completely fine, so it must be a problem with me specific PC and not something I'm doing wrong. Do you have any idea what could be causing it? I have the correct python and vc++ redis versions.

**Comment by Skarsnik** [comment]
You can give a try to the Bizhawk or RetroArch support.
