### ISSUE TITLE
[QFile2Snes] Fix Directory Issues

### ISSUE THREAD

**Issue by codemann8** [Skarsnik/QUsb2snes#31]
The 'New Directory' button doesn't do anything when pressed.  Also, when you drag and drop a folder onto the window, instead of a new directory showing up, a file shows up with the filename matching the directory name (no file extension) and doesn't function as a directory.  The contents of which are unknown, but unusable.  The only way I'm able to get a new directory onto the SD card is by pulling the SD card out of the SD2SNES and plugging it into a card reader and creating the directory thru Windows.

**Comment by Skarsnik** [comment]
This should be fixed
