### ISSUE TITLE
[SNES Classic] Support for Retroarch/Snes9x

### ISSUE THREAD

**Issue by cheuer** [Skarsnik/QUsb2snes#34]
I recently installed a Super Storage so that I could use MSU on the snes classic, but when I tried to do a multiworld I couldn't get QUsb2snes to connect. I assume this is because it only works with the default emulator, canoe. Would it be possible to add support for snes9x?

**Comment by Skarsnik** [comment]
You can use the Retroarch support with the snes classic, you just need to find the config file to enable network command support then specify the snes classic ip in Qusb2snes config, It's just not directly documented x)

**Comment by cheuer** [comment]
Thanks, I had some issues getting it working but it looks like the key was disabling snes classic support and enabling the retroarch one. I also set RetroArchHost=device_ip in the config.ini and enabled the network command support in retroarch itself as you suggested.
