### ISSUE TITLE
Port change

### ISSUE THREAD

**Issue by qwertymodo** [Skarsnik/QUsb2snes#35]
Anybody who has ever done webdev will tell you that port 8080 is really crowded, and should only be used for local dev, and not in the release build of an app, in order to avoid conflicts. The websocket server port should definitely be changed to something else. KatDevsGames has implemented a USB2SNES websocket server into the Crowd Control client using port 64213, so for the sake of interoperability, I would suggest using that.  I've also filed an issue with https://github.com/RedGuyyyy/usb2snesw/issues/2 as well, so hopefully this change can be adopted as the new standard port across the board.

**Comment by Skarsnik** [comment]
8080 is not crowded on an user system. And it's not that easy, since QUsb2Snes goal is to not break existing stuff. I legit don't see the real need for this, since so far the only conflict people reported me were usb2snes server running in CC

**Comment by qwertymodo** [comment]
Streamlabs ChatBot listens on port 8080, which hard crashes QUSB2SNES if it's opened first. Same with a bunch of dev tools.

**Comment by qwertymodo** [comment]
In any case, port 8080 is specified by convention as an alternative HTTP webserver port. (Q)USB2SNES is not an HTTP webserver, and should not be using that port, for the same reason it shouldn't be using 80, or 443, or 22.

**Comment by Skarsnik** [comment]
More discussions should occur on https://github.com/usb2snes/usb2snes/issues/1 
I leave this issue open for when I will change QUsb2Snes for this

**Comment by tcprescott** [comment]
I just want to say that the odds of RedGuyyyy making any additional updates to his usb2snes WebSocket server implementation is pretty bleak.

I don't see any reason why the qusb2snes project can't bind to both ports for backward compatibility.  If port 8080 is in use, it simply doesn't bind to the port and only bind to 64213.

**Comment by Skarsnik** [comment]
Done in f06b303

**Comment by qwertymodo** [comment]
The commit message had me worried since I thought we'd settled on 23074, but it looks like that's what's actually in the code. Thanks.
