### ISSUE TITLE
[QFile2Snes] ROM deployment and booting from the commandline.

### ISSUE THREAD

**Issue by mephitisdeux** [Skarsnik/QUsb2snes#37]
What is says on the tin. I can get **QUSB2Snes** running fine on (Arch) Linux, and **QFile2Snes** works great as well. The issue however, is when developing ROMs, it would be nice to have a simple command to deploy, and then run a ROM from the command-line. For those who use editors like VS Code, or what have you, being able to use something like a [Task](https://code.visualstudio.com/Docs/editor/tasks) to assemble, deploy, and run a ROM on hardware in one go would be invaluable.

Is the already a low-level option to do this, or would this essentially be a feature request?

**Comment by Skarsnik** [comment]
I could add that to QFile2Snes or the Binary that allow to send rom directly to the sd2snes (and boot them).

**Comment by jowijo** [comment]
> I could add that to QFile2Snes or the Binary that allow to send rom directly to the sd2snes (and boot them).

That would be neat. Being able to just write `QFile2Snes --nogui -o <rom.smc>` would be sweet and simple.

**Comment by Skarsnik** [comment]
See project : https://github.com/usb2snes/usb2snes-cli
