### ISSUE TITLE
Browsing error with QFile2Snes & QUsb2Snes, Linux

### ISSUE THREAD

**Issue by j-whitehouse** [Skarsnik/QUsb2snes#41]
Hello!

I git cloned QUsb2snes & compiled it on my local system, following the Linux ReadMe worked fine, along with the stty command. I have 1.10.3-usb-v11 firmware on my sd2snes in a SuperNT. I can start up the web socket server (no difference as my user or root) & qfile2snes, and get the initial listing of top level directories correctly (so far so good). However, if I attempt to browse / click into a directory I get the following error from QUsb2snes:

```
            WSServer : "QFile2Snes" received  "{\n    \"Opcode\": \"List\",\n    \"Operands\": [\n        \"/Kaizo\"\n    ],\n    \"Space\": \"SNES\"\n}\n"
            WSServer : Request is  USB2SnesWS::List
            WSServer : Device is  ADevice::READY
            WSServer : Executing request :  8 Created at QTime("04:51:56.058") - USB2SnesWS::List SD2Snes::SNES () ("/Kaizo") WSServer::RequestState::NEW for "QFile2Snes"
             SD2SNES : CMD :  SD2Snes::LS SD2Snes::FILE 0 "/Kaizo"
             SD2SNES : >> "5553424104000000" - 252-272 :  "000000002f4b61697a6f00000000000000000000"
             SD2SNES : Written :  512  bytes
            WSServer : Request executed
             SD2SNES : SP Received:  128  ( 512 )
             SD2SNES : Protocol error: "\x00\x00\x00\x00\x00\x00"
            WSServer : Device Error "SD2SNES ttyACM0"
            WSServer : Cleaning up device  "SD2SNES ttyACM0"
            WSServer : Error with a ws client  "QFile2Snes" WSServer::DeviceError "Device closed"
            WSServer : Websocket disconnected "QFile2Snes"
            WSServer : Cleaning up wsocket "QFile2Snes"
      SD2SNESFactory : Delete  "SD2SNES ttyACM0"
```

I receive a largely similar issue using other web socket client programs. I'm hoping I've messed up in a known way! Otherwise, what should I do to look into this problem further?

**Comment by Skarsnik** [comment]
It's a bug in the code that I need to fix, you can maybe try the fork
proposed in the current pull request trying to fix it :)

Le lun. 2 déc. 2019 à 12:55, j-whitehouse <notifications@github.com> a
écrit :

**Comment by j-whitehouse** [comment]
Fast response :grin:  Thank you! That worked, I'm able to use the romloader script & QFile now, seemed to do the trick. Glad I didn't have to figure it out, C++ is not my specialty. 

Now I to figure out why my homebrew code displays sprites differentl between bsnes & my real system. That's my own problem to solve. Thank you again, do you have a tip jar or Patreon?
