### ISSUE TITLE
AutoTracking not working since 0.7.12

### ISSUE THREAD

**Issue by Unknownforce351** [Skarsnik/QUsb2snes#44]
Been having problems with Autotracking using retroarch + bsnes since the new versions (worked fine in 0.7.11).  Drilled into changes and narrowed the problem to the following 2 lines/changes in devices/retroarchfactory.cpp

```
line 63    m_sock->write(QByteArray("READ_CORE_RAM 40FFC0 32"));
line 88    hasSnesLoromMap = rInfos->type == LoROM;
```

Reverting these to the following resolved the problem for me.  Not sure if it's proper, but it resolves my issues.

```
line 63    m_sock->write(QByteArray("READ_CORE_RAM FFC0 32"));
line 88    hasSnesLoromMap = !rom_info_make_sense(rInfos, HiROM);
```

**Comment by Skarsnik** [comment]
For what game? a LoROM rom? like alttp ?

**Comment by Unknownforce351** [comment]
SM/ALTTP Combo  ExHiRom

**Comment by Skarsnik** [comment]
This should work now?

**Comment by Unknownforce351** [comment]
Yup, works good now.
