### ISSUE TITLE
QUsb2snes is suspended

### ISSUE THREAD

**Issue by Jotthew** [Skarsnik/QUsb2snes#46]
I've been trying to play alttpr multiworld with a friend, but qusb2snes keeps getting suspended.

Emulator: snes9x 1.6
OS: Windows 10

**Comment by Skarsnik** [comment]
You mean it crashs?
Can you activate the debug log and run a session until it crashs and paste it somewhere (debug-log.tx)

**Comment by Jotthew** [comment]
I had meant that the process was being suspended by windows and needed to be restarted through task manager, but shortly after posting this I found out that it was the antivirus I forgot I had that was causing the issue.
