### ISSUE TITLE
Request: qusb2snes by default should listen on 64213 tcp as well as 8080 tcp

### ISSUE THREAD

**Issue by tcprescott** [Skarsnik/QUsb2snes#48]
A new multiworld service for ALTTP Randomizer will be accessing the sd2snes bridge on 64213, instead of 8080.  We feel that 8080 is too common of a port and more often than not causes conflicts with those running services also listening on port 8080.

If qusb2snes could also be set up to listen on 64213/tcp, that would be awesome.  It would align with the ports the Crowd Control usb2snes service listens on as well (8080 and 64213).

If you have any questions, please let me know.

**Comment by Skarsnik** [comment]
See https://github.com/usb2snes/usb2snes/issues/1
