### ISSUE TITLE
SD2SNES incompatibiliy with ALTTPR Multiworld

### ISSUE THREAD

**Issue by Berserker66** [Skarsnik/QUsb2snes#53]
So, using https://github.com/Berserker66/MultiWorld-Utilities/releases of version 2.2.1 apparently this works fine with SD2SNES. Releases since only work with emulator bridges and SD2SNES bridges specifically crash when receiving an item (write to memory).

I don't have more data than that, lacking an SD2SNES myself.

**Comment by Skarsnik** [comment]
You probably should clarify what is the software that crash and what bridge are you talking about. I am not sure to understand your issue x)

**Comment by Berserker66** [comment]
Well I don't know the nitty details myself as the people who have the issues don't go here to report them. Here's a copy of a conversation which hopefully helps.
![image](https://user-images.githubusercontent.com/3189725/86498484-4a6ac500-bd86-11ea-863d-b2f35c303686.png)
![image](https://user-images.githubusercontent.com/3189725/86498492-58b8e100-bd86-11ea-84a6-07316aca5850.png)
![image](https://user-images.githubusercontent.com/3189725/86498504-61a9b280-bd86-11ea-9ab6-bef52a0feeb6.png)

**Comment by Skarsnik** [comment]
It's most likely an user error or you are naivly trying to just write in memory like it work on emulator but on sd2snes you don't know want write will happen, it's not guaranty at the start of the frame or something

**Comment by zig-for** [comment]
Updating this - I tracked this down to an issue with VPUT - there's some sort of issue with this block: https://github.com/Skarsnik/QUsb2snes/blob/master/devices/sd2snesdevice.cpp#L309 where `m_size` doesn't get set to 0, so the device is forever stuck in BUSY state. I'm going to try and binary search to find the broken commit, but that requires me to spend a few hours with someone with actual hardware (or someone to send me a SNES and the cart).
