### ISSUE TITLE
QUsb2snes v0.7.19 to SD2SNES is not returning correct memory values.

### ISSUE THREAD

**Issue by trippsc2** [Skarsnik/QUsb2snes#65]
I'm running QUsb2snes on Manjaro Linux.  Since upgrading to v0.7.19, memory checks are returning incorrect and rapidly changing results when connecting to an SD2SNES.  I've attached the debug log below.

Reverting to v0.7.18 returns functionality to normal.

[log-debug.txt](https://github.com/Skarsnik/QUsb2snes/files/5409295/log-debug.txt)

**Comment by Skarsnik** [comment]
This should be fixed in last git version.

**Comment by trippsc2** [comment]
The debug log I provided was with the latest commit.  The issue does not appear to be fixed.

**Comment by trippsc2** [comment]
After doing a clean build to verify, I get the same result.  New log attached.

[log-debug.txt](https://github.com/Skarsnik/QUsb2snes/files/5409537/log-debug.txt)

**Comment by Skarsnik** [comment]
I mean the last git commit, not the latest release, I fixed a similar issue
but did not do a release yet.

**Comment by trippsc2** [comment]
I understood what you meant.  The original issue was generated with the latest version of the master branch compiled from source.  I rebuilt again to verify this.  The issue is not fixed.

**Comment by Skarsnik** [comment]
I tried running a stress test with 10 clients doing 1000 request or one client doing 10000 request and no issue so far. I will try on my Linux env later

**Comment by black-sliver** [comment]
Is this still a problem for you?

For me commit 0649ecd fixed most issues on Arch, but a different change in v0.7.19 will make QUsb send partial data back to the application (i.e. application requests 512 bytes, qusb will reply 2x 256 bytes), which is fine with TCP, but may reveal bugs in applications. Menblock's secret of mana rando tracker for example does not like this.

**Comment by trippsc2** [comment]
I haven't tested since my last reply, because I hadn't seen any updates.  I'll give it a try later today and see if I see something similar.  I will also try limiting requests to 256 bytes and see if that makes a difference.  It's possible that there is an issue in my app when fetching larger datasets.

**Comment by trippsc2** [comment]
I reduced the maximum data requested to 256 bytes and tested on the latest version of Qusb2snes from the AUR (displays v7.19.3) and still see the same rapidly changing values.  This behavior is only occurring on an SD2SNES setup, not using Retroarch.
