### ISSUE TITLE
Not working with retroarch 1.9.1

### ISSUE THREAD

**Issue by IronNash** [Skarsnik/QUsb2snes#88]
I don't know if it's an issue on retroarch end but I can't get it to work with the 1.9.1 version. It worked as intended on 1.9.0

**Comment by black-sliver** [comment]
https://github.com/libretro/RetroArch/issues/12262

There is also the possibility that we get 1.9.1 compatibility in a future QUsb2snes, but that's not done yet.

**Comment by bmarwell** [comment]
It's a known, but not documented bug. Appearantly, qusb2snes was using an API call which worked perfectly but was never never to work that way. When this was "fixed" in RA 1.9.1, qusb stopped working.
But we opened an issue there, and RA 1.9.2 will be working again. 

As @black-sliver mentioned, new versions of qusb will close this one-version gap.

**Comment by IronNash** [comment]
RA 1.9.2 is out and it was not fixed, any workaround?

**Comment by bmarwell** [comment]
Hmmm. It did get merged though. Maybe yet another issue?

We'd need debug logs for better analysis.

Also, the only known workaround is to use 1.9.0.
