### ISSUE TITLE
Cannot read /home/pi/QUsb2snes/EmuNWAccess-qt/EmuNWAccess-qt.pri: No such file or directory

### ISSUE THREAD

**Issue by TheTommynator** [Skarsnik/QUsb2snes#89]
I'm trying to set up QUsb2snes using this guide for my retropie:
https://www.reddit.com/r/alttpr/comments/ewy4di/multiworld_on_retropie_raspberry_pi/

But where it says run:
qmake -qt=5 QUsb2snes.pro CONFIG+='release'

All I get is this error:
Cannot read /home/pi/QUsb2snes/EmuNWAccess-qt/EmuNWAccess-qt.pri: No such file or directory

The directory exists but there is no EmuNWAccess-qt.pri
What should be in this file?

**Comment by Skarsnik** [comment]
First, you should probably build from tagged release and not master


To fix your issue you can do

```shell
git submodule init
git submodule update
```

Also, I recommend adding `"QUSB2SNES_NOGUI=1"` to your qmake invocation so you don't need a xserver on your raspberry pi.
